
---
output:
  word_document: default
  html_document: default
  pdf_document: default
---

# Estado: Gasto y Tributación

## Gasto público, impuestos y deuda

Tomemos como punto de partida la identidad del ingreso nacional^[Para simplificar suponemos que la renta neta de factores es cero]
\begin{equation}
Y=C+I+G+X-M
\end{equation}

Si restamos a ambos lados los impuestos, $T$, y después de reorganizar los términos tenemos

\begin{equation}
(T-G)+(Y-T-C-I)+(M-X)=0
\end{equation}

Esta identidad nos dice que la suma del ahorro público, ahorro privado y ahorro externo es cero. Luego, si el gasto público, $G$, excede a los impuestos, $T$, entonces la suma del ahorro privado y externo debe ser positiva. Ello quiere decir que el déficit público es compensado con un superávit primario o usando ahorro del resto del mundo. En las cuentas fiscales esto se refleja en la emisión de deuda interna y/o externa. 

## Sobre el rol del Estado en la economía

¿Cómo surge el Estado? Una explicación tiene que ver con la amenaza de la violencia organizada. Así, la jerarquía y el Estado podrían haber surgido cuando un grupo tribal conquista a otro y obtiene el control territorial. Mantener el control sobre los conquistados en un incentivo muy fuerte para producir instituciones instituciones centralizadas capaces de ejercer represión y dominio amplio. A su vez, la amenazada de ser conquistado puede llevar a que varios grupos tribales relacionados acuerden ceder parte de su autoridad a una forma de mando centralizada a fin de lograr una coordinación efectiva en tiempo de guerra. Claro, esto no quiere decir que la violencia entre tríbus diese lugar de manera inexorable al surgimiento de Estados, ni que todos los estados hayan nacido de la guerra @fukuyama2011. Sin embargo, como dice el historiador Ian Morris en su libro *Guerra ¿Para qué sirve?*  "la guerra hace al Estado y el Estado hace la guerra" @morris2017

Se cual fuese la explicación correcta, lo cierto es que el Estado existe y ejerce influencia sobre el sistema económico y nuestra vida cotidiana. Dado que este existe, la pregunta es entonces ¿Cuál **debe** ser el papel del Estado en la economía? Note que la pregunta no es ¿Cuál **es** el rol del Estado? Así, la primera indagación es de carácter normativo, estamos buscando es una *justificación*, un juicio valorativo a partir del cual llegamos a concluir que el Estado debe hacer esto y aquello. La segunda pregunta es de un alcance más limitado, ella solo nos pide una descripción de las cosas tal cual son, independientemente de si consideramos que así es como estas deberían ser.

Si tomamos como punto de partida las funciones mínimas que el Estado desempeña para garantizar su permanencia, a saber, el uso de de la coerción para mantener el control de la población y el territorio, entonces esperamos que esto corresponda a la provisión de los servicios de seguridad, defensa y justicia. El Estado es los suficientemente fuerte como para reducir la violencia y garantizar el cumplimiento de los acuerdos entre los miembros de la sociedad.  De ahí en adelante el alcance de la acción del Estado puede extenderse considerablemente ¿Qué tanto? La posición predominante entre los economistas es que e Estado debe actuar allí donde el mercado falla. 

Si el mercado es un mecanismo que asigna los recursos productivos de la sociedad para la producción de bienes y servicios, en variedad y cantidad tal que permite la satisfacción de las multitud de preferencias individuales, y si este mecanismo es superior a otros alternativos, entonces decimos que falla cuando no produce resultados satisfactorios. Es decir, resulta en la producción de mucho de aquello que no queremos, ej. contaminación, y muy poco de aquello que deseamos, ej. servicios de salud de calidad. En economía se suele hablar de las siguientes fallas

- Externalidad: los agentes no incorporan en sus decisiones la totalidad de los costos (beneficios) que conlleva su acción y por lo tanto los traslada, involuntariamente, a otros consumidores y/o productores. 

- Bienes no privados: ausencia de rivalidad y/o exclusión

- Asimetrias de información: una de las partes en la transacción sabe algo relevante que la otra parte no sabe

- Estructuras de mercado no competitivas: otorga poder de fijación de precios

Además de las fallas de mercado, la ampliación del ámbito de acción del Estado se ha justificado también porque de alguna manera se considera que este debe redistribuir recursos para que la sociedad sea más equitativa. A fin de cuentas el mercado asigna recursos tomando como dada la estructura distributiva tal cual, sin preguntarse por la justicia de esta. En asocio con esto tenemos la idea según la cual hay ciertos bienes, como la educación, que se consideran socialmente deseables y que por lo tanto, se argumenta, deben ser provistos directamente por el Estado, o con su intervención, para garantizar que no hay barreras para acceder a ellos.  

La corrección de las fallas y la redistribución la logra el Estado a través de: 1) la regulación de la actividad económica, ej. controlando precios; 2) el uso de impuestos y subsidios; 3) provisión directa de bienes y servicios; 4) financiación de la demanda. 

Las corrientes de pensamiento liberal que desconfían profundamente en la capacidad del Estado para alcanzar los objetivos que se propone y respetar las libertades individuales ven en esta narrativa de fallas del mercado demasiadas instancias de intervención estatal. Por ejemplo, @mccloskey2016 afirma 

> "The fact suggest that the projects of betterment enacted by governments, compared with voluntary >deals made among consenting adults free of force or fraud, will fail, as they regularly have, because >they are directed not at general betterment but at enriching special interests at the expense of the >generality, or merely spending what money the government can appropriate under the threat of violence"
>
>`r tufte::quote_footer('--- Deirdre McCloskey')`

Aún si los individuos que integran el Estado son las personas más altruistas e idealistas, ¿cómo pueden saber ellos cuales son los mejores usos de los recursos disponibles de la sociedad? Esta, una de las observaciones fundamentales de Hayek, es una difícil cuestión que todo defensor de la planeación económica debe enfrentar. 

En contraposición, los economistas cercanos al progresismo creen que el gobierno es capaz de controlar la economía y guiarla en la dirección deseada. Dicen @mitchell2019 "(...) los gobiernos siempre pueden escoger y mantener una tasa de desempleo particular (...) entendemos que la economía solo servirá nuestros propósitos comunes si está sujeta a la vigilancia y control". 

Así, frente a la pregunta inicial, ¿Cuál **debe** ser el papel del Estado en la economía?, debe quedar claro que estamos lejos de un consenso sobre el asunto. En la práctica, lo que el Estado termina haciendo es un resultado, un producto de la interacción entre los agentes de la sociedad y las condiciones externas. Veamos el caso Colombiano

## ¿Cuánto gasta y en qué gasta el gobierno Colombiano?

Como sabemos del capítulo anterior, el Estado es más que el gobierno, sin embargo, desde el punto de vista de la ejecución de gasto público este es el más importante. Así, en lo que sigue haremos énfasis en el gobierno central, aunque mostraremos algunas cifras para otras instancias del sector público.  


```{r, echo=FALSE, message=FALSE, warning=FALSE,fig.cap="Ingresos y gastos GNC. Fuente: Plan Financiero 2020"}
library(flextable)
Concepto<-c("Ingresos totales","Tributarios", "No Tributarios", "Fondos especiales", "Recursos de capital", "Gastos totales", "Intereses", "Funcionamiento", "Inversión", "Balance Total")
Y2019Bn<-c(171.8, 148.4,1.5,1.5,20.5,197.9,30.8,149.4,17.9,-26)
Y2019PIB<-c(16.5,14.3,0.1,0.1,2.0,19,3,14.3,1.7,-2.5)

df<-data.frame(Concepto,Y2019Bn,Y2019PIB)
myft<-flextable(df)
bft<-bold(myft,i=1, part="header")
bft<-bold(bft,i=c(1,6,10))
bft<-theme_zebra(bft)
bft<-set_header_labels(bft,Y2019Bn="2019 ($Bn)",Y2019PIB="2019 (%PIB)")
bft <- set_table_properties(bft, layout = "autofit", width = .5)
bft


```

