# Dinero y Precios

## Introducción 

En este módulo se abordará la idea de dinero y su relación con el comportamiento del nivel de precios de la economía.

## ¿Qué es el dinero?

En la actualidad la creación de dinero es monopolio de los gobiernos nacionales, sin embargo, eso no siempre ha sido así, y no tiene porque seguir siendo así. Empecemos por intentar definir el término dinero. Si buscamos en el diccionario de la Real Academía Española encontramos que es definido como moneda corriente. Pero eso no nos lleva muy lejos en nuestro intento de comprender. F.A Hayek, por ejemplo, se lamenta que intentemos describir el dinero como un sustantivo. Sugiere que lo veamos como un adjetivo que describe una propiedad que diferentes cosas tienen en diferente grado @hayek76. Cuando hablamos de dinero hacemos referencia a las funciones que cumple. Unidad de cuenta, medio de pago, y depósito de valor. De esta manera, a lo largo de la historia de la humanidad se han usado múltiples objetos para cumplir estas funciones. Por ejemplo, las conchas marinas, *Cypraea*, fueron usadas comúnmente por las caravanas de comerciantes árabes en [África occidental](https://www.culturesofwestafrica.com/cowrie-shell-monetary-symbolic-value/). 

En el caso de América Latina se dice que durante la colonia coexistieron las monedas españolas con las diferentes monedas locales indígenas, como los granos de cacao.  Las monedas españolas eran principalmente acuñadas en plata y la unidad usualmente usada era el peso fuerte de plata. En los inicios de la historia de Colombia como república independiente circularon simultáneamente diversas especies monetarias y los billetes emitidos por bancos privados, los cuales eran redimibles por moneda metálica^[Antono Hernández Gamarra, Las especies monetarias en Colombia, 2016, http://www.revistacredencial.com/credencial/historia/temas/las-especies-monetarias-en-colombia]. 

Desde la creación del Banco de la República en 1923, la emisión de dinero, peso colombiano, ha sido monopolio de esta entidad. Hasta 1931 los billetes emitidos por eran redimibles por su equivalente en oro. Así, dado que las cosas que usamos como dinero no tienen ningún valor intrínseco decimos que lo que circula es dinero fiduciario. Tienen valor porque confiamos en el que alguien más las aceptará al momento de realizar una transacción por el valor que simboliza. Es un sistema basado en la confianza.

Es importante decir que el sistema monetario es más que la circulación de dinero. Si usted piensa en una transacción en la que se intercambia dinero en forma de monedas por un bien o servicio, se dará cuenta que para el receptor de las monedas es evidente que está recibiendo algo por el valor acordado a cambio del objeto, y que esas mismas monedas no están siendo utilizadas en ese mismo momento para realizar otra transacción. Ahora, si usted piensa en un pago electrónico se dará cuenta que eso ya no es evidente. Requerimos un sistema de información lo suficientemente robusto para asegurarnos que el comprador tiene saldo en su cuenta y que ese saldo no está siendo utilizado para algo más. Hasta hace algunos años cuando los cheques eran más comunes el proceso de verificación, *clearing*, tomaba 3 días. En la actualidad el sistema monetario es complejo y en él intervienen múltiples entidades. 

Si bien para nosostros el orden normal de las cosas es una moneda única emitida por el Banco Central, esto no es la regla que ha prevalecido en las sociedades humanas. De hecho, en la historia reciente de Latinoamérica el dólar ha reemplazado a las monedas de circulación legal en algunos países en momentos de inestabilidad macroeconómica. Si la gente no confía, la moneda simplemente no sirve, no importa lo que diga el gobierno. 

En la actualidad, el monopolio de emisión de dinero está siendo puesto a prueba por las llamadas criptomonedas. Ciertamente han ido ganando un espacio en los portafolios de inversión, y como medio de pago empiezan a ser aceptadas ¿Podemos considerarlas dinero?, si lo son o llegan a serlo, ¿Cuáles son las implicaciones para el ejercicio de la política monetaria? Estas son cuestiones contemporáneas de interés e importancia. 



```{r, echo=FALSE, warning=FALSE, message=FALSE,fig.cap="Cripto monedas, Yahoo Finance"}
library(quantmod)
start<-as.Date("2017-01-01")
end<-as.Date("2021-03-12")

getSymbols("BTC-USD",src="yahoo", from=start, to=end)
getSymbols("ETH-USD",src="yahoo", from=start, to=end)

library(dygraphs)
btc1<-dygraph(`BTC-USD`[,"BTC-USD.Close"],main="Bitcoin-precio de cierre (USD)")
btc1
eth1<-dygraph(`ETH-USD`[,"ETH-USD.Close"],main="Ethereum-precio de cierre (USD)")%>%
  dyOptions(colors="red")
eth1
```

## Nivel de precios, IPC e inflación
